version: '3'

services:
    php-app:
        build:
            context: ./Dockerfile
        depends_on:
            - mysql
            - nginx
            - php-fpm
        container_name: ${PROJECT_NAME}
        command: sh bin/build.sh

    nginx:
        build:
            context: docker/nginx/Dockerfile
        volumes:
            - .:/app
        container_name: ${PROJECT_NAME}-nginx
        restart: always
        ports:
                - "8081:80"
                - "443:443"

    php-fpm:
        build:
            context: docker/php-fpm/Dockerfile
        volumes:
            - .:/app
        container_name: ${PROJECT_NAME}-php-fpm

    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - mysql:/var/lib/mysql
        container_name: ${PROJECT_NAME}-mysql
        environment:
            MYSQL_DATABASE: library
            MYSQL_ROOT_PASSWORD: password

volumes:
    mysql: